const express=require('express');
const router=express.Router();
const control=require('../Controller/controller');
// const auth = require('./auth');
const { relativeTimeRounding } = require('moment');
// router.get('/detail',auth.verifyToken,auth.verifyRole(['Admin','Consumer']),control.Details);
router.get('/user/details',control.Details);
router.post('/signup',control.Signup);
router.post('/mail',control.Mail);
router.post('/login',control.Login);
router.post('/otp',control.Signupverification);
router.post('/otp/verification',control.Otp_verification);
router.post('/forget/password',control.ForgotPassword);
router.patch('/forget/password',control.ChangePassword);
router.post('/scheme/master',control.SchemeMasterInsert);
router.patch('/scheme/master',control.SchemeMasterUpdate);
router.get('/scheme/master',control.SchemeMasterDetails);
router.post('/scheme/amount/master',control.SchemeAmountMasterInsert);
router.patch('/scheme/amount/master',control.SchemeAmountMasterUpdate);
router.get('/scheme/amount/master',control.SchemeAmountMasterDetails);
module.exports=router;